<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BookCatalog;
use Carbon\Carbon;

class BookCatalogSeeder extends Seeder
{
    public function run(): void {
        BookCatalog::insert([
            [
                'category_id' => 3,
                'title' => 'Aisyah-Aqilah',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Aisyah-Aqilah.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Aisyah-Aqilah',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'title' => 'Akankah-Dia-Menjadi-Milikku',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Akankah-Dia-Menjadi-Milikku.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Akankah-Dia-Menjadi-Milikku',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 10,
                'title' => 'Ayah-Untuk-Nolan',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Ayah-Untuk-Nolan.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Ayah-Untuk-Nolan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Dear-Allah-2',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Dear-Allah-2.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Dear-Allah-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 6,
                'title' => 'Dear-Allah-3',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Dear-Allah-3.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Dear-Allah-3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Diary-Syabil',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Diary-Syabil.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Diary-Syabil',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 3,
                'title' => 'Hi-Ustadz-Agam',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Hi-Ustadz-Agam.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Hi-Ustadz-Agam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Istri-Kedua-Gus-Tampan',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Istri-Kedua-Gus-Tampan.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Istri-Kedua-Gus-Tampan',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 3,
                'title' => 'Janji-Yang-Ternoda',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Janji-Yang-Ternoda.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Janji-Yang-Ternoda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Jean-Senja',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Jean-Senja.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Jean-Senja',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 10,
                'title' => 'Jodohku-Yang-Mana',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Jodohku-Yang-Mana.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Jodohku-Yang-Mana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Kalam-Cinta-Sang-Gus',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Kalam-Cinta-Sang-Gus.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Kalam-Cinta-Sang-Gus',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 10,
                'title' => 'Khariza',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Khariza.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Khariza',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Love-Kitchen',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Love-Kitchen.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Love-Kitchen',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 3,
                'title' => 'My-Cold-Sky',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'My-Cold-Sky.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'My-Cold-Sky',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Orang-Yang-Sama',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Orang-Yang-Sama.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Orang-Yang-Sama',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 10,
                'title' => 'Sangsaka',
                'writer' => 'Kim Jong Un',
                'thick' => '2 cm',
                'length' => '20 cm',
                'width' => '15 cm',
                'image' => 'Sangsaka.png',
                'launch_at' => Carbon::create('2024', '10', '01'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Sangsaka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'title' => 'Suamiku-Ustaz-Dingin',
                'writer' => 'Mellyana Dhian',
                'thick' => '3 cm',
                'length' => '22 cm',
                'width' => '17 cm',
                'image' => 'Suamiku-Ustaz-Dingin.png',
                'launch_at' => Carbon::create('2023', '05', '15'),
                'glimpse' => 'First, make sure CryptoJS is correctly imported. The crypto-js library exports its functionality in a way that might not always align with the default import syntax. You can try using a different import method.',
                'slug' => 'Suamiku-Ustaz-Dingin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
